// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISignatureVerifier$Type } from "./ISignatureVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISignatureVerifier"]: ISignatureVerifier$Type;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/ISignatureVerifier.sol:ISignatureVerifier"]: ISignatureVerifier$Type;
  }

  interface ContractTypesMap {
    ["ISignatureVerifier"]: GetContractReturnType<ISignatureVerifier$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/ISignatureVerifier.sol:ISignatureVerifier"]: GetContractReturnType<ISignatureVerifier$Type["abi"]>;
  }
}
