// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPCCSRouter$Type } from "./IPCCSRouter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPCCSRouter"]: IPCCSRouter$Type;
    ["@inco/lightning/src/interfaces/automata-interfaces/IPCCSRouter.sol:IPCCSRouter"]: IPCCSRouter$Type;
  }

  interface ContractTypesMap {
    ["IPCCSRouter"]: GetContractReturnType<IPCCSRouter$Type["abi"]>;
    ["@inco/lightning/src/interfaces/automata-interfaces/IPCCSRouter.sol:IPCCSRouter"]: GetContractReturnType<IPCCSRouter$Type["abi"]>;
  }
}
