// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IConfidentialERC20$Type } from "./IConfidentialERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IConfidentialERC20"]: IConfidentialERC20$Type;
    ["contracts/ConfidentialERC20/Interfaces/IConfidentialERC20.sol:IConfidentialERC20"]: IConfidentialERC20$Type;
  }

  interface ContractTypesMap {
    ["IConfidentialERC20"]: GetContractReturnType<IConfidentialERC20$Type["abi"]>;
    ["contracts/ConfidentialERC20/Interfaces/IConfidentialERC20.sol:IConfidentialERC20"]: GetContractReturnType<IConfidentialERC20$Type["abi"]>;
  }
}
