// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ITEELifecycle$Type } from "./ITEELifecycle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ITEELifecycle"]: ITEELifecycle$Type;
    ["@inco/lightning/src/lightning-parts/interfaces/ITEELifecycle.sol:ITEELifecycle"]: ITEELifecycle$Type;
  }

  interface ContractTypesMap {
    ["ITEELifecycle"]: GetContractReturnType<ITEELifecycle$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/interfaces/ITEELifecycle.sol:ITEELifecycle"]: GetContractReturnType<ITEELifecycle$Type["abi"]>;
  }
}
