// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEncryptedInput$Type } from "./IEncryptedInput";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEncryptedInput"]: IEncryptedInput$Type;
    ["@inco/lightning/src/lightning-parts/interfaces/IEncryptedInput.sol:IEncryptedInput"]: IEncryptedInput$Type;
  }

  interface ContractTypesMap {
    ["IEncryptedInput"]: GetContractReturnType<IEncryptedInput$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/interfaces/IEncryptedInput.sol:IEncryptedInput"]: GetContractReturnType<IEncryptedInput$Type["abi"]>;
  }
}
