// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IEncryptedInput$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IEncryptedInput",
  "sourceName": "@inco/lightning/src/lightning-parts/interfaces/IEncryptedInput.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "ciphertext",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "newEaddress",
      "outputs": [
        {
          "internalType": "eaddress",
          "name": "newValue",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "ciphertext",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "newEbool",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "newValue",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "ciphertext",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "newEuint256",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "newValue",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IEncryptedInput",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEncryptedInput$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/IEncryptedInput.sol:IEncryptedInput",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEncryptedInput$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IEncryptedInput",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEncryptedInput$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/IEncryptedInput.sol:IEncryptedInput",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEncryptedInput$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IEncryptedInput",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEncryptedInput$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/IEncryptedInput.sol:IEncryptedInput",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEncryptedInput$Type["abi"]>>;
}
