// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { HangmanFactory$Type } from "./HangmanFactory";
import { HangmanGame$Type } from "./HangmanGame";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HangmanFactory"]: HangmanFactory$Type;
    ["HangmanGame"]: HangmanGame$Type;
    ["contracts/IncoHangMan.sol:HangmanFactory"]: HangmanFactory$Type;
    ["contracts/IncoHangMan.sol:HangmanGame"]: HangmanGame$Type;
  }

  interface ContractTypesMap {
    ["HangmanFactory"]: GetContractReturnType<HangmanFactory$Type["abi"]>;
    ["HangmanGame"]: GetContractReturnType<HangmanGame$Type["abi"]>;
    ["contracts/IncoHangMan.sol:HangmanFactory"]: GetContractReturnType<HangmanFactory$Type["abi"]>;
    ["contracts/IncoHangMan.sol:HangmanGame"]: GetContractReturnType<HangmanGame$Type["abi"]>;
  }
}
