// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { USDC$Type } from "./USDC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["USDC"]: USDC$Type;
    ["contracts/ERC20.sol:USDC"]: USDC$Type;
  }

  interface ContractTypesMap {
    ["USDC"]: GetContractReturnType<USDC$Type["abi"]>;
    ["contracts/ERC20.sol:USDC"]: GetContractReturnType<USDC$Type["abi"]>;
  }
}
