// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC20Metadata$Type } from "./IERC20Metadata";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20Metadata"]: IERC20Metadata$Type;
    ["contracts/ConfidentialERC20/Utils/IERC20Metadata.sol:IERC20Metadata"]: IERC20Metadata$Type;
  }

  interface ContractTypesMap {
    ["IERC20Metadata"]: GetContractReturnType<IERC20Metadata$Type["abi"]>;
    ["contracts/ConfidentialERC20/Utils/IERC20Metadata.sol:IERC20Metadata"]: GetContractReturnType<IERC20Metadata$Type["abi"]>;
  }
}
