// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConfidentialERC20Wrapper$Type } from "./ConfidentialERC20Wrapper";
import { IERC20extended$Type } from "./IERC20extended";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConfidentialERC20Wrapper"]: ConfidentialERC20Wrapper$Type;
    ["IERC20extended"]: IERC20extended$Type;
    ["contracts/ConfidentialERC20Wrapper.sol:ConfidentialERC20Wrapper"]: ConfidentialERC20Wrapper$Type;
    ["contracts/ConfidentialERC20Wrapper.sol:IERC20extended"]: IERC20extended$Type;
  }

  interface ContractTypesMap {
    ["ConfidentialERC20Wrapper"]: GetContractReturnType<ConfidentialERC20Wrapper$Type["abi"]>;
    ["IERC20extended"]: GetContractReturnType<IERC20extended$Type["abi"]>;
    ["contracts/ConfidentialERC20Wrapper.sol:ConfidentialERC20Wrapper"]: GetContractReturnType<ConfidentialERC20Wrapper$Type["abi"]>;
    ["contracts/ConfidentialERC20Wrapper.sol:IERC20extended"]: GetContractReturnType<IERC20extended$Type["abi"]>;
  }
}
