// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EncryptedOperations$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EncryptedOperations",
  "sourceName": "@inco/lightning/src/lightning-parts/EncryptedOperations.sol",
  "abi": [
    {
      "inputs": [],
      "name": "EnforcedPause",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "ExpectedPause",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "FeeNotPaid",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "FeeWithdrawalFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "InvalidInitialization",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint8",
          "name": "raw",
          "type": "uint8"
        }
      ],
      "name": "InvalidTypeValue",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "NoFeesToWithdraw",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "NotInitializing",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "verifyingContract",
          "type": "address"
        },
        {
          "internalType": "bytes4",
          "name": "callFunction",
          "type": "bytes4"
        },
        {
          "internalType": "bytes",
          "name": "argData",
          "type": "bytes"
        }
      ],
      "name": "ProofVerificationFailed",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "enum ETypes",
          "name": "t",
          "type": "uint8"
        }
      ],
      "name": "SameTypeCast",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "name": "SenderNotAllowedForHandle",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "enum ETypes",
          "name": "actual",
          "type": "uint8"
        },
        {
          "internalType": "bytes32",
          "name": "expectedTypes",
          "type": "bytes32"
        }
      ],
      "name": "UnexpectedType",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "enum ETypes",
          "name": "actual",
          "type": "uint8"
        }
      ],
      "name": "UnsupportedType",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "Allow",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EAdd",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EBitAnd",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EBitOr",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EBitXor",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "ct",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "uint8",
          "name": "toType",
          "type": "uint8"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ECast",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EDiv",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EEq",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EGe",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EGt",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "ebool",
          "name": "control",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "ifTrue",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "ifFalse",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EIfThenElse",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ELe",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ELt",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EMax",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EMin",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EMul",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ENe",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "operand",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ENot",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "counter",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "enum ETypes",
          "name": "randType",
          "type": "uint8"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "upperBound",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ERandBounded",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ERem",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ERotl",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ERotr",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EShl",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "EShr",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "ESub",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint64",
          "name": "version",
          "type": "uint64"
        }
      ],
      "name": "Initialized",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "Paused",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "eventId",
          "type": "uint256"
        }
      ],
      "name": "Reveal",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "Unpaused",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allow",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowTransient",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowedTransient",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "sharer",
              "type": "address"
            },
            {
              "components": [
                {
                  "internalType": "string",
                  "name": "warning",
                  "type": "string"
                },
                {
                  "internalType": "bytes32",
                  "name": "sessionNonce",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "verifyingContract",
                  "type": "address"
                },
                {
                  "internalType": "bytes4",
                  "name": "callFunction",
                  "type": "bytes4"
                },
                {
                  "internalType": "bytes",
                  "name": "sharerArgData",
                  "type": "bytes"
                }
              ],
              "internalType": "struct AllowanceVoucher",
              "name": "voucher",
              "type": "tuple"
            },
            {
              "internalType": "bytes",
              "name": "voucherSignature",
              "type": "bytes"
            },
            {
              "internalType": "bytes",
              "name": "requesterArgData",
              "type": "bytes"
            }
          ],
          "internalType": "struct AllowanceProof",
          "name": "proof",
          "type": "tuple"
        }
      ],
      "name": "claimHandle",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eAdd",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eBitAnd",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eBitOr",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eBitXor",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "ct",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "toType",
          "type": "uint8"
        }
      ],
      "name": "eCast",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eDiv",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eEq",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eGe",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eGt",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "ebool",
          "name": "control",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "ifTrue",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "ifFalse",
          "type": "bytes32"
        }
      ],
      "name": "eIfThenElse",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eLe",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eLt",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eMax",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eMin",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eMul",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eNe",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "ebool",
          "name": "operand",
          "type": "bytes32"
        }
      ],
      "name": "eNot",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "upperBound",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "randType",
          "type": "uint8"
        }
      ],
      "name": "eRandBounded",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eRem",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eRotl",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eRotr",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eShl",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eShr",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eSub",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getBitFee",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint16",
          "name": "nOfElements",
          "type": "uint16"
        },
        {
          "internalType": "enum ETypes",
          "name": "elType",
          "type": "uint8"
        }
      ],
      "name": "getEListFee",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getEventCounter",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getFee",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getNextEventId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "enum EOps",
          "name": "op",
          "type": "uint8"
        },
        {
          "internalType": "enum ETypes",
          "name": "returnType",
          "type": "uint8"
        },
        {
          "internalType": "bytes",
          "name": "packedInputs",
          "type": "bytes"
        }
      ],
      "name": "getOpResultHandle",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "generatedHandle",
          "type": "bytes32"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "plaintextBytes",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "handleType",
          "type": "uint8"
        }
      ],
      "name": "getTrivialEncryptHandle",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "generatedHandle",
          "type": "bytes32"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "incoVerifier",
      "outputs": [
        {
          "internalType": "contract IIncoVerifier",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        }
      ],
      "name": "isRevealed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "paused",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "persistAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        }
      ],
      "name": "reveal",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EncryptedOperations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EncryptedOperations$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/EncryptedOperations.sol:EncryptedOperations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EncryptedOperations$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EncryptedOperations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EncryptedOperations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/EncryptedOperations.sol:EncryptedOperations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EncryptedOperations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EncryptedOperations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EncryptedOperations$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/EncryptedOperations.sol:EncryptedOperations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EncryptedOperations$Type["abi"]>>;
}
