// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIncoVerifier$Type } from "./IIncoVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIncoVerifier"]: IIncoVerifier$Type;
    ["@inco/lightning/src/interfaces/IIncoVerifier.sol:IIncoVerifier"]: IIncoVerifier$Type;
  }

  interface ContractTypesMap {
    ["IIncoVerifier"]: GetContractReturnType<IIncoVerifier$Type["abi"]>;
    ["@inco/lightning/src/interfaces/IIncoVerifier.sol:IIncoVerifier"]: GetContractReturnType<IIncoVerifier$Type["abi"]>;
  }
}
