// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IQuoteVerifier$Type } from "./IQuoteVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IQuoteVerifier"]: IQuoteVerifier$Type;
    ["@inco/lightning/src/interfaces/automata-interfaces/IQuoteVerifier.sol:IQuoteVerifier"]: IQuoteVerifier$Type;
  }

  interface ContractTypesMap {
    ["IQuoteVerifier"]: GetContractReturnType<IQuoteVerifier$Type["abi"]>;
    ["@inco/lightning/src/interfaces/automata-interfaces/IQuoteVerifier.sol:IQuoteVerifier"]: GetContractReturnType<IQuoteVerifier$Type["abi"]>;
  }
}
