// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IQuoteVerifier$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IQuoteVerifier",
  "sourceName": "@inco/lightning/src/interfaces/automata-interfaces/IQuoteVerifier.sol",
  "abi": [
    {
      "inputs": [],
      "name": "pccsRouter",
      "outputs": [
        {
          "internalType": "contract IPCCSRouter",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "quoteVersion",
      "outputs": [
        {
          "internalType": "uint16",
          "name": "",
          "type": "uint16"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "uint16",
              "name": "version",
              "type": "uint16"
            },
            {
              "internalType": "bytes2",
              "name": "attestationKeyType",
              "type": "bytes2"
            },
            {
              "internalType": "bytes4",
              "name": "teeType",
              "type": "bytes4"
            },
            {
              "internalType": "bytes2",
              "name": "qeSvn",
              "type": "bytes2"
            },
            {
              "internalType": "bytes2",
              "name": "pceSvn",
              "type": "bytes2"
            },
            {
              "internalType": "bytes16",
              "name": "qeVendorId",
              "type": "bytes16"
            },
            {
              "internalType": "bytes20",
              "name": "userData",
              "type": "bytes20"
            }
          ],
          "internalType": "struct Header",
          "name": "",
          "type": "tuple"
        },
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "name": "verifyQuote",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        },
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "name": "verifyZkOutput",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        },
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IQuoteVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IQuoteVerifier$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/interfaces/automata-interfaces/IQuoteVerifier.sol:IQuoteVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IQuoteVerifier$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IQuoteVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IQuoteVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/interfaces/automata-interfaces/IQuoteVerifier.sol:IQuoteVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IQuoteVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IQuoteVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IQuoteVerifier$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/interfaces/automata-interfaces/IQuoteVerifier.sol:IQuoteVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IQuoteVerifier$Type["abi"]>>;
}
