// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDecryptionAttester$Type } from "./IDecryptionAttester";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDecryptionAttester"]: IDecryptionAttester$Type;
    ["@inco/lightning/src/lightning-parts/interfaces/IDecryptionAttester.sol:IDecryptionAttester"]: IDecryptionAttester$Type;
  }

  interface ContractTypesMap {
    ["IDecryptionAttester"]: GetContractReturnType<IDecryptionAttester$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/interfaces/IDecryptionAttester.sol:IDecryptionAttester"]: GetContractReturnType<IDecryptionAttester$Type["abi"]>;
  }
}
