// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IDecryptionAttester$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IDecryptionAttester",
  "sourceName": "@inco/lightning/src/lightning-parts/interfaces/IDecryptionAttester.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "handle",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "value",
              "type": "bytes32"
            }
          ],
          "internalType": "struct DecryptionAttestation",
          "name": "decryption",
          "type": "tuple"
        }
      ],
      "name": "decryptionAttestationDigest",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "handle",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "value",
              "type": "bytes32"
            }
          ],
          "internalType": "struct DecryptionAttestation",
          "name": "decryption",
          "type": "tuple"
        },
        {
          "internalType": "bytes[]",
          "name": "signatures",
          "type": "bytes[]"
        }
      ],
      "name": "isValidDecryptionAttestation",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IDecryptionAttester",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDecryptionAttester$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/IDecryptionAttester.sol:IDecryptionAttester",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDecryptionAttester$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IDecryptionAttester",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDecryptionAttester$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/IDecryptionAttester.sol:IDecryptionAttester",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDecryptionAttester$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IDecryptionAttester",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDecryptionAttester$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/IDecryptionAttester.sol:IDecryptionAttester",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDecryptionAttester$Type["abi"]>>;
}
