// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEncryptedOperations$Type } from "./IEncryptedOperations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEncryptedOperations"]: IEncryptedOperations$Type;
    ["@inco/lightning/src/lightning-parts/interfaces/IEncryptedOperations.sol:IEncryptedOperations"]: IEncryptedOperations$Type;
  }

  interface ContractTypesMap {
    ["IEncryptedOperations"]: GetContractReturnType<IEncryptedOperations$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/interfaces/IEncryptedOperations.sol:IEncryptedOperations"]: GetContractReturnType<IEncryptedOperations$Type["abi"]>;
  }
}
