// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVersion$Type } from "./IVersion";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVersion"]: IVersion$Type;
    ["@inco/lightning/src/version/interfaces/IVersion.sol:IVersion"]: IVersion$Type;
  }

  interface ContractTypesMap {
    ["IVersion"]: GetContractReturnType<IVersion$Type["abi"]>;
    ["@inco/lightning/src/version/interfaces/IVersion.sol:IVersion"]: GetContractReturnType<IVersion$Type["abi"]>;
  }
}
