// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAdvancedAccessControl$Type } from "./IAdvancedAccessControl";
import { IVoucherEip712Checker$Type } from "./IVoucherEip712Checker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAdvancedAccessControl"]: IAdvancedAccessControl$Type;
    ["IVoucherEip712Checker"]: IVoucherEip712Checker$Type;
    ["@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IAdvancedAccessControl"]: IAdvancedAccessControl$Type;
    ["@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IVoucherEip712Checker"]: IVoucherEip712Checker$Type;
  }

  interface ContractTypesMap {
    ["IAdvancedAccessControl"]: GetContractReturnType<IAdvancedAccessControl$Type["abi"]>;
    ["IVoucherEip712Checker"]: GetContractReturnType<IVoucherEip712Checker$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IAdvancedAccessControl"]: GetContractReturnType<IAdvancedAccessControl$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IVoucherEip712Checker"]: GetContractReturnType<IVoucherEip712Checker$Type["abi"]>;
  }
}
