// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IVoucherEip712Checker$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IVoucherEip712Checker",
  "sourceName": "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "string",
              "name": "warning",
              "type": "string"
            },
            {
              "internalType": "bytes32",
              "name": "sessionNonce",
              "type": "bytes32"
            },
            {
              "internalType": "address",
              "name": "verifyingContract",
              "type": "address"
            },
            {
              "internalType": "bytes4",
              "name": "callFunction",
              "type": "bytes4"
            },
            {
              "internalType": "bytes",
              "name": "sharerArgData",
              "type": "bytes"
            }
          ],
          "internalType": "struct AllowanceVoucher",
          "name": "voucher",
          "type": "tuple"
        }
      ],
      "name": "allowanceVoucherDigest",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IVoucherEip712Checker",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVoucherEip712Checker$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IVoucherEip712Checker",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVoucherEip712Checker$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IVoucherEip712Checker",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVoucherEip712Checker$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IVoucherEip712Checker",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVoucherEip712Checker$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IVoucherEip712Checker",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVoucherEip712Checker$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IAdvancedAccessControl.sol:IVoucherEip712Checker",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVoucherEip712Checker$Type["abi"]>>;
}
