// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConfidentialToken$Type } from "./ConfidentialToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConfidentialToken"]: ConfidentialToken$Type;
    ["contracts/ConfidentialERC20/ConfidentialToken.sol:ConfidentialToken"]: ConfidentialToken$Type;
  }

  interface ContractTypesMap {
    ["ConfidentialToken"]: GetContractReturnType<ConfidentialToken$Type["abi"]>;
    ["contracts/ConfidentialERC20/ConfidentialToken.sol:ConfidentialToken"]: GetContractReturnType<ConfidentialToken$Type["abi"]>;
  }
}
