// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEventCounter$Type } from "./IEventCounter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEventCounter"]: IEventCounter$Type;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/IEventCounter.sol:IEventCounter"]: IEventCounter$Type;
  }

  interface ContractTypesMap {
    ["IEventCounter"]: GetContractReturnType<IEventCounter$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/IEventCounter.sol:IEventCounter"]: GetContractReturnType<IEventCounter$Type["abi"]>;
  }
}
