// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IEventCounter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IEventCounter",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/interfaces/IEventCounter.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getEventCounter",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getNextEventId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IEventCounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEventCounter$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IEventCounter.sol:IEventCounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEventCounter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IEventCounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEventCounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IEventCounter.sol:IEventCounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEventCounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IEventCounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEventCounter$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IEventCounter.sol:IEventCounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEventCounter$Type["abi"]>>;
}
