// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ITrivialEncryption$Type } from "./ITrivialEncryption";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ITrivialEncryption"]: ITrivialEncryption$Type;
    ["@inco/lightning/src/lightning-parts/interfaces/ITrivialEncryption.sol:ITrivialEncryption"]: ITrivialEncryption$Type;
  }

  interface ContractTypesMap {
    ["ITrivialEncryption"]: GetContractReturnType<ITrivialEncryption$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/interfaces/ITrivialEncryption.sol:ITrivialEncryption"]: GetContractReturnType<ITrivialEncryption$Type["abi"]>;
  }
}
