// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ITrivialEncryption$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ITrivialEncryption",
  "sourceName": "@inco/lightning/src/lightning-parts/interfaces/ITrivialEncryption.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "value",
          "type": "address"
        }
      ],
      "name": "asEaddress",
      "outputs": [
        {
          "internalType": "eaddress",
          "name": "newEaddress",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bool",
          "name": "value",
          "type": "bool"
        }
      ],
      "name": "asEbool",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "newEbool",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "asEuint256",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "newEuint256",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ITrivialEncryption",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ITrivialEncryption$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/ITrivialEncryption.sol:ITrivialEncryption",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ITrivialEncryption$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ITrivialEncryption",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ITrivialEncryption$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/ITrivialEncryption.sol:ITrivialEncryption",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ITrivialEncryption$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ITrivialEncryption",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ITrivialEncryption$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/interfaces/ITrivialEncryption.sol:ITrivialEncryption",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ITrivialEncryption$Type["abi"]>>;
}
