// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    Context: never;
    IERC20Metadata: never;
    IERC1155Errors: never;
    IERC20Errors: never;
    IERC721Errors: never;
    ConfidentialERC20: never;
  }

  interface ContractTypesMap {
    Context: never;
    IERC20Metadata: never;
    IERC1155Errors: never;
    IERC20Errors: never;
    IERC721Errors: never;
    ConfidentialERC20: never;
  }
}
