// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVerifierAddressGetter$Type } from "./IVerifierAddressGetter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVerifierAddressGetter"]: IVerifierAddressGetter$Type;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/IVerifierAddressGetter.sol:IVerifierAddressGetter"]: IVerifierAddressGetter$Type;
  }

  interface ContractTypesMap {
    ["IVerifierAddressGetter"]: GetContractReturnType<IVerifierAddressGetter$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/IVerifierAddressGetter.sol:IVerifierAddressGetter"]: GetContractReturnType<IVerifierAddressGetter$Type["abi"]>;
  }
}
