// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IVerifierAddressGetter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IVerifierAddressGetter",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/interfaces/IVerifierAddressGetter.sol",
  "abi": [
    {
      "inputs": [],
      "name": "incoVerifier",
      "outputs": [
        {
          "internalType": "contract IIncoVerifier",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IVerifierAddressGetter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVerifierAddressGetter$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IVerifierAddressGetter.sol:IVerifierAddressGetter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVerifierAddressGetter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IVerifierAddressGetter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVerifierAddressGetter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IVerifierAddressGetter.sol:IVerifierAddressGetter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVerifierAddressGetter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IVerifierAddressGetter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVerifierAddressGetter$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IVerifierAddressGetter.sol:IVerifierAddressGetter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVerifierAddressGetter$Type["abi"]>>;
}
