// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Fee$Type } from "./Fee";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Fee"]: Fee$Type;
    ["@inco/lightning/src/lightning-parts/Fee.sol:Fee"]: Fee$Type;
  }

  interface ContractTypesMap {
    ["Fee"]: GetContractReturnType<Fee$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/Fee.sol:Fee"]: GetContractReturnType<Fee$Type["abi"]>;
  }
}
