// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Fee$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Fee",
  "sourceName": "@inco/lightning/src/lightning-parts/Fee.sol",
  "abi": [
    {
      "inputs": [],
      "name": "FeeNotPaid",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "getFee",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Fee",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Fee$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/Fee.sol:Fee",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Fee$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Fee",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Fee$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/Fee.sol:Fee",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Fee$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Fee",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Fee$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/Fee.sol:Fee",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Fee$Type["abi"]>>;
}
