// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EventCounter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EventCounter",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getEventCounter",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getNextEventId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600e575f5ffd5b5060d580601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106030575f3560e01c80633c82a9781460345780639df5be6e14604c575b5f5ffd5b603a6072565b60405190815260200160405180910390f35b7f424e67de01535191ae441dac30ebc840d30f78dda500964a3abe35b40c86270c54603a565b5f609a7f424e67de01535191ae441dac30ebc840d30f78dda500964a3abe35b40c86270c5490565b90509056fea2646970667358221220b515728a6c7f641dc4d375a4efe32ff67470e9f45e1aa8fd6baa795cce5defa464736f6c634300081c0033",
  "deployedBytecode": "0x6080604052348015600e575f5ffd5b50600436106030575f3560e01c80633c82a9781460345780639df5be6e14604c575b5f5ffd5b603a6072565b60405190815260200160405180910390f35b7f424e67de01535191ae441dac30ebc840d30f78dda500964a3abe35b40c86270c54603a565b5f609a7f424e67de01535191ae441dac30ebc840d30f78dda500964a3abe35b40c86270c5490565b90509056fea2646970667358221220b515728a6c7f641dc4d375a4efe32ff67470e9f45e1aa8fd6baa795cce5defa464736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EventCounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EventCounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EventCounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EventCounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EventCounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/EventCounter.sol:EventCounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EventCounter$Type["abi"]>>;
}
