// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VerifierAddressGetter$Type } from "./VerifierAddressGetter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VerifierAddressGetter"]: VerifierAddressGetter$Type;
    ["@inco/lightning/src/lightning-parts/primitives/VerifierAddressGetter.sol:VerifierAddressGetter"]: VerifierAddressGetter$Type;
  }

  interface ContractTypesMap {
    ["VerifierAddressGetter"]: GetContractReturnType<VerifierAddressGetter$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/VerifierAddressGetter.sol:VerifierAddressGetter"]: GetContractReturnType<VerifierAddressGetter$Type["abi"]>;
  }
}
