// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIncoLightning$Type } from "./IIncoLightning";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIncoLightning"]: IIncoLightning$Type;
    ["@inco/lightning/src/interfaces/IIncoLightning.sol:IIncoLightning"]: IIncoLightning$Type;
  }

  interface ContractTypesMap {
    ["IIncoLightning"]: GetContractReturnType<IIncoLightning$Type["abi"]>;
    ["@inco/lightning/src/interfaces/IIncoLightning.sol:IIncoLightning"]: GetContractReturnType<IIncoLightning$Type["abi"]>;
  }
}
