// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IIncoLightning$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IIncoLightning",
  "sourceName": "@inco/lightning/src/interfaces/IIncoLightning.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allow",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowTransient",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowedTransient",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "value",
          "type": "address"
        }
      ],
      "name": "asEaddress",
      "outputs": [
        {
          "internalType": "eaddress",
          "name": "newEaddress",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bool",
          "name": "value",
          "type": "bool"
        }
      ],
      "name": "asEbool",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "newEbool",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "asEuint256",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "newEuint256",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "sharer",
              "type": "address"
            },
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "sessionNonce",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "verifyingContract",
                  "type": "address"
                },
                {
                  "internalType": "bytes4",
                  "name": "callFunction",
                  "type": "bytes4"
                },
                {
                  "internalType": "bytes",
                  "name": "sharerArgData",
                  "type": "bytes"
                }
              ],
              "internalType": "struct AllowanceVoucher",
              "name": "voucher",
              "type": "tuple"
            },
            {
              "internalType": "bytes",
              "name": "voucherSignature",
              "type": "bytes"
            },
            {
              "internalType": "bytes",
              "name": "requesterArgData",
              "type": "bytes"
            }
          ],
          "internalType": "struct AllowanceProof",
          "name": "proof",
          "type": "tuple"
        }
      ],
      "name": "claimHandle",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "cleanTransientStorage",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eAdd",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eBitAnd",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eBitOr",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eBitXor",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "ct",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "toType",
          "type": "uint8"
        }
      ],
      "name": "eCast",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eDiv",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eEq",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eGe",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eGt",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "ebool",
          "name": "condition",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "ifTrue",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "ifFalse",
          "type": "bytes32"
        }
      ],
      "name": "eIfThenElse",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eLe",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eLt",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eMax",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eMin",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eMul",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eNe",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "ebool",
          "name": "operand",
          "type": "bytes32"
        }
      ],
      "name": "eNot",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "enum ETypes",
          "name": "randType",
          "type": "uint8"
        }
      ],
      "name": "eRand",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "upperBound",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "randType",
          "type": "uint8"
        }
      ],
      "name": "eRandBounded",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eRem",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eRotl",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eRotr",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eShl",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eShr",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "euint256",
          "name": "lhs",
          "type": "bytes32"
        },
        {
          "internalType": "euint256",
          "name": "rhs",
          "type": "bytes32"
        }
      ],
      "name": "eSub",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "result",
          "type": "bytes32"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getMajorVersion",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getName",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "enum EOps",
          "name": "op",
          "type": "uint8"
        },
        {
          "internalType": "enum ETypes",
          "name": "returnType",
          "type": "uint8"
        },
        {
          "internalType": "bytes",
          "name": "packedInputs",
          "type": "bytes"
        }
      ],
      "name": "getOpResultHandle",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "generatedHandle",
          "type": "bytes32"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "plaintextBytes",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "handleType",
          "type": "uint8"
        }
      ],
      "name": "getTrivialEncryptHandle",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "generatedHandle",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getVersion",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getVersionedName",
      "outputs": [
        {
          "internalType": "string",
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "incoVerifier",
      "outputs": [
        {
          "internalType": "contract IIncoVerifier",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "owner",
          "type": "address"
        }
      ],
      "name": "initialize",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "majorVersion",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "minorVersion",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "ciphertext",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "newEaddress",
      "outputs": [
        {
          "internalType": "eaddress",
          "name": "newValue",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "ciphertext",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "newEbool",
      "outputs": [
        {
          "internalType": "ebool",
          "name": "newValue",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "ciphertext",
          "type": "bytes"
        },
        {
          "internalType": "address",
          "name": "user",
          "type": "address"
        }
      ],
      "name": "newEuint256",
      "outputs": [
        {
          "internalType": "euint256",
          "name": "newValue",
          "type": "bytes32"
        }
      ],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "patchVersion",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "persistAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "salt",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IIncoLightning",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IIncoLightning$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/interfaces/IIncoLightning.sol:IIncoLightning",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IIncoLightning$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IIncoLightning",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IIncoLightning$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/interfaces/IIncoLightning.sol:IIncoLightning",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IIncoLightning$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IIncoLightning",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IIncoLightning$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/interfaces/IIncoLightning.sol:IIncoLightning",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IIncoLightning$Type["abi"]>>;
}
