// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IBaseAccessControlList$Type } from "./IBaseAccessControlList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBaseAccessControlList"]: IBaseAccessControlList$Type;
    ["@inco/lightning/src/lightning-parts/AccessControl/interfaces/IBaseAccessControlList.sol:IBaseAccessControlList"]: IBaseAccessControlList$Type;
  }

  interface ContractTypesMap {
    ["IBaseAccessControlList"]: GetContractReturnType<IBaseAccessControlList$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/AccessControl/interfaces/IBaseAccessControlList.sol:IBaseAccessControlList"]: GetContractReturnType<IBaseAccessControlList$Type["abi"]>;
  }
}
