// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IBaseAccessControlList$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IBaseAccessControlList",
  "sourceName": "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IBaseAccessControlList.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allow",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowTransient",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "allowedTransient",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "sharer",
              "type": "address"
            },
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "sessionNonce",
                  "type": "bytes32"
                },
                {
                  "internalType": "address",
                  "name": "verifyingContract",
                  "type": "address"
                },
                {
                  "internalType": "bytes4",
                  "name": "callFunction",
                  "type": "bytes4"
                },
                {
                  "internalType": "bytes",
                  "name": "sharerArgData",
                  "type": "bytes"
                }
              ],
              "internalType": "struct AllowanceVoucher",
              "name": "voucher",
              "type": "tuple"
            },
            {
              "internalType": "bytes",
              "name": "voucherSignature",
              "type": "bytes"
            },
            {
              "internalType": "bytes",
              "name": "requesterArgData",
              "type": "bytes"
            }
          ],
          "internalType": "struct AllowanceProof",
          "name": "proof",
          "type": "tuple"
        }
      ],
      "name": "claimHandle",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "cleanTransientStorage",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "incoVerifier",
      "outputs": [
        {
          "internalType": "contract IIncoVerifier",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "handle",
          "type": "bytes32"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "persistAllowed",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IBaseAccessControlList",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IBaseAccessControlList$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IBaseAccessControlList.sol:IBaseAccessControlList",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IBaseAccessControlList$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IBaseAccessControlList",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IBaseAccessControlList$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IBaseAccessControlList.sol:IBaseAccessControlList",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IBaseAccessControlList$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IBaseAccessControlList",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IBaseAccessControlList$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/AccessControl/interfaces/IBaseAccessControlList.sol:IBaseAccessControlList",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IBaseAccessControlList$Type["abi"]>>;
}
