// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IHandleGeneration$Type } from "./IHandleGeneration";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IHandleGeneration"]: IHandleGeneration$Type;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/IHandleGeneration.sol:IHandleGeneration"]: IHandleGeneration$Type;
  }

  interface ContractTypesMap {
    ["IHandleGeneration"]: GetContractReturnType<IHandleGeneration$Type["abi"]>;
    ["@inco/lightning/src/lightning-parts/primitives/interfaces/IHandleGeneration.sol:IHandleGeneration"]: GetContractReturnType<IHandleGeneration$Type["abi"]>;
  }
}
