// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IHandleGeneration$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IHandleGeneration",
  "sourceName": "@inco/lightning/src/lightning-parts/primitives/interfaces/IHandleGeneration.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "enum EOps",
          "name": "op",
          "type": "uint8"
        },
        {
          "internalType": "enum ETypes",
          "name": "returnType",
          "type": "uint8"
        },
        {
          "internalType": "bytes",
          "name": "packedInputs",
          "type": "bytes"
        }
      ],
      "name": "getOpResultHandle",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "generatedHandle",
          "type": "bytes32"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "plaintextBytes",
          "type": "bytes32"
        },
        {
          "internalType": "enum ETypes",
          "name": "handleType",
          "type": "uint8"
        }
      ],
      "name": "getTrivialEncryptHandle",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "generatedHandle",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IHandleGeneration",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IHandleGeneration$Type["abi"]>>;
  export function deployContract(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IHandleGeneration.sol:IHandleGeneration",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IHandleGeneration$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IHandleGeneration",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IHandleGeneration$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IHandleGeneration.sol:IHandleGeneration",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IHandleGeneration$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IHandleGeneration",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IHandleGeneration$Type["abi"]>>;
  export function getContractAt(
    contractName: "@inco/lightning/src/lightning-parts/primitives/interfaces/IHandleGeneration.sol:IHandleGeneration",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IHandleGeneration$Type["abi"]>>;
}
